title: ZEKAI Docs
description: Documenting & Sharing
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-include-cache

# Optional configuration
color_scheme: light
search_enabled: true
  

